### ISSUE TITLE
important

### ISSUE THREAD

**Issue by ardadasdelen** [slorixsh/Spotify-Follower-Sender#1]
an important matter please look into it urgently

spotify followers build but not follow

**Comment by slorixsh** [comment]
> an important matter please look into it urgently
> 
> spotify followers build but not follow

give your spotify profile link. like : https://open.spotify.com/user/31hxzbr53fgc4klna4llls7jn3jm?si=e134fc36358541e6

**Comment by ardadasdelen** [comment]
I need a video on how to install and use

**Comment by slorixsh** [comment]
> I need a video on how to install and use

contact me on dc slorixsh#0148
